apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: my-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: springboot-container
          image: himanshutha/myimage:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80         # external port
      targetPort: 8081 # internal container port
      nodePort: 30093  # exposed on EC2 node

