apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
