apiVersion: v1
kind: Service
metadata:
  name: star-agile-banking-service
  labels:
    app: star-agile-banking
spec:
  selector:
    app: star-agile-banking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
